### ISSUE TITLE
ERROR: API Base ID fetch failed: API Base ID pattern not found

### ISSUE THREAD

**Issue by deyman12** [Galkurta/Clayton-BOT#10]
could not login after clayton recently maintenance, and they also give compensation. i think they change something (maybe). kindly check it ! thanks.
```
2024-11-22 18:16:24 | ERROR | API Base ID fetch failed: API Base ID pattern not found
2024-11-22 18:16:24 | ERROR | Failed to initialize API Base ID. Retrying in 1 minute...
2024-11-22 18:17:24 | ERROR | API Base ID fetch failed: API Base ID pattern not found
2024-11-22 18:17:24 | ERROR | Failed to initialize API Base ID. Retrying in 1 minute...
```

**Comment by desvianus** [comment]
same issue
![Screenshot from 2024-11-22 18-45-59](https://github.com/user-attachments/assets/4803768b-4fd2-4679-92e1-c541e833dc9b)

**Comment by deyman12** [comment]
> same issue ![Screenshot from 2024-11-22 18-45-59](https://private-user-images.githubusercontent.com/1453116/388922406-4803768b-4fd2-4679-92e1-c541e833dc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzY3NjEsIm5iZiI6MTczMjI3NjQ2MSwicGF0aCI6Ii8xNDUzMTE2LzM4ODkyMjQwNi00ODAzNzY4Yi00ZmQyLTQ2NzktOTJlMS1jNTQxZTgzM2RjOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTE1NDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ0NzI2Yjg5ZmM2MDAyYmI2OTJkYWMwNzFmMzlkNTcyNjhkZGFiZTI0YmMyMWVkNWIyZjhkZGM4ZTMwZTIxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WVsXQTgh39YK3P7sCVUIx8S7STWviUdqQ4t7ZT3KSA8)

@Galkurta pls check!

**Comment by hikarkun** [comment]
Please Update Api @Galkurta Thanks

**Comment by Valgri** [comment]
who is looking for a solution - **change** 
`const match = jsContent.match(/_ge="([^"]+)"/);`
to
` const match = jsContent.match(/sCe="([^"]+)"/);`

**Comment by deyman12** [comment]
> who is looking for a solution - **change** `const match = jsContent.match(/_ge="([^"]+)"/);` to ` const match = jsContent.match(/sCe="([^"]+)"/);`

solved!!, it was quick and easy. but the author didn’t take any action at all.

**Comment by Valgri** [comment]
the minimized code changed each day probably.
So you need setup 
const match = jsContent.match(/Ife="([^"]+)"/) || ['', 'your-api-id'];`

How to get your-api-id ?
Open tg in web version
Click F12 ( the developer tab should open)
Find in the top - network tab
Run Clayton bot in tg web version
You should see the authorization request (https://tonclayton.fun/api/{your-api-id}/user/authorization)
Copy this ID and past in the code as mentioned above.

**Comment by Valgri** [comment]
> > the minimized code changed each day probably. So you need setup const match = jsContent.match(/Ife="([^"]+)"/) || ['', 'your-api-id'];`
> > How to get your-api-id ? Open tg in web version Click F12 ( the developer tab should open) Find in the top - network tab Run Clayton bot in tg web version You should see the authorization request ([https://tonclayton.fun/api/{your-api-id}/user/authorization](https://tonclayton.fun/api/%7Byour-api-id%7D/user/authorization)) Copy this ID and past in the code as mentioned above.
> 
> the variable name where the API ID is stored always changes, ya, that’s true. so just need to find that variable name to get the API ID. that should’ve been resolved in my pull request. #11 this issue have been solved, and i close it!

Cool! Approved. Maybe the owner can merge it now.
